---
# tasks file for dotfiles
- include: dependencies.yml

- name: create group
  group: name=robert state=present

- name: create user
  user:
    name: robert
    createhome: yes
    home: /home/robert/
    state: present

- authorized_key: user={{ robert_username }} key={{ robert_key }}

- name: check groups
  shell: /usr/bin/getent group | awk -F":" '{print $1}'
  register: register_robert_etc_groups
  changed_when: false

- name: add secondary groups
  user: name={{ robert_username }} groups={{ item }} append=yes
  when: '"{{ item }}" in register_robert_etc_groups.stdout_lines'
  with_items:
    - mail
    - docker

- name: add keyboard interactive group
  user: name={{ robert_username }} groups={{ robert_keyboard_interactive_group }} append=yes
  when: robert_keyboard_interactive_group is defined and robert_keyboard_interactive_group != ""

- name: fetch and install dotfiles
  git:
    repo: https://github.com/paerallax/dotfiles
    clone: yes
  shell: ./manage install
    chdir: dotfiles
  args:
    executable: /bin/bash
    
- name: install NVM
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  become: true
  become_user: robert
  args:
    executable: /bin/bash
    creates: /home/robert/.nvm
    warn: no

- name: install NodeJS
  shell: bash -lc 'nvm install 7.5.0'
  become: true
  become_user: robert
  args:
    creates: /home/robert/.nvm/versions/7.5.0
    warn: no

# - name: install Rust
#   shell: curl https://sh.rustup.rs -sSf | sh
#   become: true
#   become_user: robert
#   args:
#     executable: /bin/bash
#     creates: /home/robert/.rust
