---
# tasks file for dotfiles
- include: dependencies.yml
- name: create group
  group: name=robert state=present

# - name: create user
#   user:
#     name: robert
#     createhome: yes
#     groups: wheel
#     home: /home/robert/
#     state: present

- name: install NVM
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  become: true
  become_user: robert
  args:
    executable: /bin/bash
    creates: /home/robert/.nvm
    warn: no

- name: install NodeJS
  shell: curl --silent --location https://rpm.nodesource.com/setup_7.x | bash
  become: true
  become_user: robert
  args:
    creates: /home/robert/.node
    warn: no

# - name: install Rust
#   shell: curl https://sh.rustup.rs -sSf | sh
#   become: true
#   become_user: robert
#   args:
#     executable: /bin/bash
#     creates: /home/robert/.rust
